# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content2',
        ),
    ]
